# 配置文件请严格遵循yaml语法格式，yaml学习地址:
#  https://ansible-tran.readthedocs.io/en/latest/docs/YAMLSyntax.html
#  http://einverne.github.io/post/2015/08/yaml.html

# 定时时间、
alarm_timed: '00:31'

# 格言渠道
# 1 : ONE●一个
# 2 : 词霸（每日英语）
dictum_channel: 2

girlfriend_infos:
  -
    #女友微信昵称/备注/账号均可
    wechat_name: '暮雪'
    #女友所在北京
    city_name: '武汉'
    # 从那天开始勾搭的（可空）
    start_date: '2020-01-01'
    # 短句的最后留言（可空）
    sweet_words: '越努力越幸运'

#  -
#    #女友微信昵称/备注/账号均可
#    wechat_name: '冷小寒'
#    #女友所在北京
#    city_name: '武汉'
#    # 从那天开始勾搭的（可空）
#    start_date: '2019-04-12'
#    # 短句的最后留言（可空）
#    sweet_words: '来自技术宅二狗。'

  #如果有你多个人需要发送，则参照这个样式，复制即可
  #-
   # wechat_name: '陈老师'
    #city_name: '朝阳区'
    #start_date: '2018-11-11'
    #sweet_words: '来自你俊美的老公。'

repley_infos:
  - 
    name: '暮雪'

